### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dannyfritz** [skuttleman/skuttleman.github.io#1]
Hi Ben!

I love the hover over interactivity of your site! Excited! Terrified!

Perfect use of a GitHub page! :+1: 

That's a pretty cool audio player you wrote up there. Switches album art and everything.

I also got a hearty chuckle out of `if (e == m * Math.pow(c, 2)) science();`.

Excited to see you in class. :smile:

**Comment by skuttleman** [comment]
Thanks! Excited/terrified to be in class.

~ ben
